# Generated by Django 5.1.3 on 2024-11-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_volunteer_facebook_url_volunteer_linkedin_url_and_more'),
    ]

    operations = [
    ]
