# Generated by Django 5.1.3 on 2024-11-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_postcomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
